---
abstract: 'a data toolkit'
author:
  - 'Nicolas Steenlant, C<< <nicolas.steenlant at ugent.be> >>'
build_requires:
  Log::Any::Adapter: '0.11'
  Log::Any::Test: '0.15'
  Module::Build: '0.3601'
  Test::Deep: '0.112'
  Test::Exception: '0.32'
  Test::More: '1.001003'
  Test::Pod: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.017, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
optional_features:
  tidy:
    description: 'Support pretty printing compiled fix code'
    requires:
      Perl::Tidy: '0'
recommends:
  JSON::XS: '2.3'
  Log::Any::Adapter::Log4perl: '0.06'
  Log::Log4perl: '1.44'
requires:
  App::Cmd: '0.323'
  CGI::Expand: '2.02'
  Clone: '0.31'
  Config::Onion: '1.004'
  Data::Compare: '1.22'
  Data::UUID: '1.217'
  Data::Util: '0.59'
  File::Find::Rule: '0.33'
  IO::Handle::Util: '0.01'
  JSON: '2.51'
  List::MoreUtils: '0.33'
  Log::Any: '0.15'
  Log::Any::Adapter: '0.11'
  Marpa::R2: '2.084000'
  Module::Info: '0'
  Moo: '1.004006'
  Sub::Exporter: '0.982'
  Sub::Quote: '0'
  Text::CSV: '1.21'
  Throwable: '0.200004'
  Time::HiRes: '0'
  Time::Piece: '0'
  Try::Tiny::ByClass: '0.01'
  YAML::XS: '0.41'
  namespace::clean: '0.24'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu/issues
  homepage: https://github.com/LibreCat/Catmandu
  repository: https://github.com/LibreCat/Catmandu.git
version: '0.9206'
x_contributors:
  - 'Christian Pietsch <chr.pietsch+github@googlemail.com>'
  - 'Dave Sherohman <Dave.Sherohman@lub.lu.se>'
  - 'Dave Sherohman <Dave.Sherohman@ub.lu.se>'
  - 'EC2 Default User <ec2-user@ip-10-113-18-155.ec2.internal>'
  - 'EC2 Default User <ec2-user@ip-10-114-199-125.ec2.internal>'
  - 'EC2 Default User <ec2-user@ip-10-194-230-16.ec2.internal>'
  - 'EC2 Default User <ec2-user@ip-10-77-5-148.ec2.internal>'
  - 'Jakob Voss <jakob@nichtich.de>'
  - 'Jakob Voss <voss@gbv.de>'
  - 'Nicolas <nicolas.steenlant@ugent.be>'
  - 'Nicolas Franck <nicolas.franck@ugent.be>'
  - 'Nicolas Steenlant <nicolas.steenlant@gmail.com>'
  - 'Nicolas Steenlant <nsteenla@ca20c608.ugent.be>'
  - 'Nicolas Steenlnat <nicolas.steenlant@ugent.be>'
  - 'Patrick <phochste@hal.lub.lu.se>'
  - 'Patrick Hochstenbach <Patrick.Hochstenbach@UGent.be>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
  - 'Snorri Briem <Snorri.Briem@lub.lu.se>'
  - 'Snorri Briem <Snorri.Briem@ub.lu.se>'
  - 'Vitali Peil <vitali.peil@uni-bielefeld.de>'
  - 'phochste <phochste@vmtemp4.ugent.be>'
  - 'vpeil <vitali.peil@uni-bielefeld.de>'
